### PR TITLE
PR3 PR4 and feature calculation script improvements

### PR DESCRIPTION
**Pull request by manics**
Fixes in response to comments on #3 including:
- Declaring JS variable correctly
- Larger error messages

This requires pyslid with icaoberg/pyslid#4 to fix the incorrect pyslid C/Z/T [Trac 11098](https://trac.openmicroscopy.org.uk/ome/ticket/11098).

Additional feature calculation script improvements:
- Less verbose messages in activities dialog
- Advanced feature calculation options are now in a separate section of the script dialog, including:
- Provide option to calculate features without updating the central ContentDB, this allows multiple feature calculation processes to be run in parallel but requires the Rebuild ContentDB script to be manually run afterwards.
  - Skip testing this if you want, since it's for expert users only.

Fixes for the ContentDB rebuild script [Trac #11010](http://trac.openmicroscopy.org.uk/ome/ticket/11010)
- If you _want_ to test this probably the best way is to delete all features, run the ContentDB rebuild script (which will now create an empty ContentDB), create your features selecting the `Disable ContentDB Update` option, then run the ContentDB rebuild script. Then check everything works.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Logged in as searcher-1. Group searcher-1.
Chose three .avi files. (pre-impoprted from the last time)
- The Feature calculation script runs now fine without errors to the end - just the deprecation warnings are there
- The Advanced features box in the feature calculation script (see screenshot below) is a bit confusing - `Enable advanced features` - what does it actually enable ? - the three sub-boxes in this field seem to be enabled anyway
  For example if I do not tick the `Enable advanced features`, but tick the `Recalculate features` box -> do I recalculate the features or not ? - if yes, why to have the `Enable advanced features` box at all ? I think this needs a bit of redesign, in order not to throughly confuse the user (albeit an advanced one).

**Comment by pwalczysko** [comment]
Went through the workflow suggested in the header of this PR. 
When doing the step `create your features selecting the Disable ContentDB Update option`, hit following bug.
In the Feature Creation script window I clicked `Run Script`. Nothing at all happened, the window was there without any changes, the `Run Script` button was still clickable. So I clicked it again. To my surprise, two actions in the Activities started to go on. The former activity finished first, with just deprecation warnings. The latter (=higher) actiivty finished second, with some error - see error and screenshot below.
screen shot 2013-06-13 at 11 02 28

```
/usr/lib64/python2.6/site-packages/mahotas/texture.py:6: DeprecationWarning: Use

from mahotas.features import texture

  ''', DeprecationWarning)
/usr/lib64/python2.6/site-packages/mahotas/zernike.py:6: DeprecationWarning: Use

from mahotas.features import zernike

  ''', DeprecationWarning)
/usr/lib64/python2.6/site-packages/mahotas/tas.py:6: DeprecationWarning: Use

from mahotas.features import tas

  ''', DeprecationWarning)
/usr/lib64/python2.6/site-packages/mahotas/lbp.py:6: DeprecationWarning: Use

from mahotas.features import lbp

  ''', DeprecationWarning)
WARNING:omero.gateway:OptimisticLockException on <class 'omero.gateway.OmeroGatewaySafeCallWrapper'> to <ed326e43-ba3a-4665-85f9-c8de3ce02946omero.api.IUpdate> saveObject((object #0 (::omero::model::TagAnnotation)
{
    _id = object #1 (::omero::RLong)
    {
        _val = 2341
    }
    _details = object #2 (::omero::model::Details)
    {
        _owner = object #3 (::omero::model::Experimenter)
        {
            _id = object #4 (::omero::RLong)
            {
                _val = 3
            }
            _details = <nil>
            _loaded = False
            _version = <nil>
            _groupExperimenterMapSeq = 
            {
            }
            _groupExperimenterMapLoaded = False
            _omeName = <nil>
            _firstName = <nil>
            _middleName = <nil>
            _lastName = <nil>
            _institution = <nil>
            _email = <nil>
            _annotationLinksSeq = 
            {
            }
            _annotationLinksLoaded = False
            _annotationLinksCountPerOwner = 
            {
            }
        }
        _group = object #5 (::omero::model::ExperimenterGroup)
        {
            _id = object #6 (::omero::RLong)
            {
                _val = 7
            }
            _details = object #7 (::omero::model::Details)
            {
                _owner = <nil>
                _group = <nil>
                _creationEvent = <nil>
                _updateEvent = <nil>
                _permissions = object #8 (::omero::model::Permissions)
                {
                    _restrictions = 
                    {
                        [0] = False
                        [1] = True
                        [2] = True
                        [3] = True
                    }
                    _perm1 = -40
                }
                _externalInfo = <nil>
                _call = 
                {
                    key = omero.session.uuid
                    value = 52557c6f-1a6e-448c-8b46-cb9bf8084b90

                    key = omero.client.uuid
                    value = ed326e43-ba3a-4665-85f9-c8de3ce02946
                }
                _event = object #9 (::omero::sys::EventContext)
                {
                    shareId = -1
                    sessionId = 1379
                    sessionUuid = 52557c6f-1a6e-448c-8b46-cb9bf8084b90
                    userId = 3
                    userName = searcher-1
                    groupId = 7
                    groupName = searcher-1
                    isAdmin = False
                    eventId = -1
                    eventType = User
                    memberOfGroups = 
                    {
                        [0] = 3
                        [1] = 1
                        [2] = 7
                    }
                    leaderOfGroups = 
                    {
                        [0] = 7
                    }
                    groupPermissions = object #10 (::omero::model::Permissions)
                    {
                        _restrictions = 
                        {
                        }
                        _perm1 = -40
                    }
                }
            }
            _loaded = True
            _version = object #11 (::omero::RInt)
            {
                _val = 0
            }
            _name = object #12 (::omero::RString)
            {
                _val = searcher-1
            }
            _groupExperimenterMapSeq = 
            {
            }
            _groupExperimenterMapLoaded = False
            _annotationLinksSeq = 
            {
            }
            _annotationLinksLoaded = False
            _annotationLinksCountPerOwner = 
            {
            }
            _description = <nil>
        }
        _creationEvent = object #13 (::omero::model::Event)
        {
            _id = object #14 (::omero::RLong)
            {
                _val = 68679
            }
            _details = <nil>
            _loaded = False
            _status = <nil>
            _time = <nil>
            _experimenter = <nil>
            _experimenterGroup = <nil>
            _type = <nil>
            _containingEvent = <nil>
            _logsSeq = 
            {
            }
            _logsLoaded = False
            _session = <nil>
        }
        _updateEvent = object #15 (::omero::model::Event)
        {
            _id = object #16 (::omero::RLong)
            {
                _val = 68682
            }
            _details = <nil>
            _loaded = False
            _status = <nil>
            _time = <nil>
            _experimenter = <nil>
            _experimenterGroup = <nil>
            _type = <nil>
            _containingEvent = <nil>
            _logsSeq = 
            {
            }
            _logsLoaded = False
            _session = <nil>
        }
        _permissions = object #17 (::omero::model::Permissions)
        {
            _restrictions = 
            {
            }
            _perm1 = -40
        }
        _externalInfo = <nil>
        _call = 
        {
            key = omero.session.uuid
            value = 52557c6f-1a6e-448c-8b46-cb9bf8084b90

            key = omero.client.uuid
            value = ed326e43-ba3a-4665-85f9-c8de3ce02946
        }
        _event = object #18 (::omero::sys::EventContext)
        {
            shareId = -1
            sessionId = 1379
            sessionUuid = 52557c6f-1a6e-448c-8b46-cb9bf8084b90
            userId = 3
            userName = searcher-1
            groupId = 7
            groupName = searcher-1
            isAdmin = False
            eventId = -1
            eventType = User
            memberOfGroups = 
            {
                [0] = 3
                [1] = 1
                [2] = 7
            }
            leaderOfGroups = 
            {
                [0] = 7
            }
            groupPermissions = object #19 (::omero::model::Permissions)
            {
                _restrictions = 
                {
                }
                _perm1 = -40
            }
        }
    }
    _loaded = True
    _version = <nil>
    _ns = object #20 (::omero::RString)
    {
        _val = direct.edu.cmu.cs.compbio.omepslid:all_slf33
    }
    _description = <nil>
    _annotationLinksSeq = 
    {
    }
    _annotationLinksLoaded = False
    _annotationLinksCountPerOwner = 
    {
    }
    _textValue = object #21 (::omero::RString)
    {
        _val = 7_all_slf33_content_db_00000000000000000003.pkl
    }
},), {})
Traceback (most recent call last):
  File "/opt/omero/server/lib/python/omero/gateway/__init__.py", line 3457, in __call__
    return self.f(*args, **kwargs)
  File "/opt/omero/server/lib/python/omero_api_IUpdate_ice.py", line 107, in saveObject
    return _M_omero.api.IUpdate._op_saveObject.invoke(self, ((obj, ), _ctx))
OptimisticLockException: exception ::omero::OptimisticLockException
{
    serverStackTrace = ome.conditions.OptimisticLockException: You are not authorized to change the update event for ome.model.annotations.TagAnnotation:Id_2341 from ome.model.meta.Event:Id_68717 to ome.model.meta.Event:Id_68682
You may need to reload the object before continuing.
    at ome.security.basic.OmeroInterceptor.managedEvent(OmeroInterceptor.java:1003)
    at ome.security.basic.OmeroInterceptor.checkManagedDetails(OmeroInterceptor.java:773)
    at ome.security.basic.OmeroInterceptor.resetDetails(OmeroInterceptor.java:316)
    at ome.security.basic.OmeroInterceptor.onFlushDirty(OmeroInterceptor.java:181)
    at org.hibernate.event.def.DefaultFlushEntityEventListener.invokeInterceptor(DefaultFlushEntityEventListener.java:372)
    at org.hibernate.event.def.DefaultFlushEntityEventListener.handleInterception(DefaultFlushEntityEventListener.java:349)
    at org.hibernate.event.def.DefaultFlushEntityEventListener.scheduleUpdate(DefaultFlushEntityEventListener.java:287)
    at org.hibernate.event.def.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:155)
    at org.hibernate.event.def.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:219)
    at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:99)
    at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
    at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1208)
    at ome.logic.UpdateImpl.afterUpdate(UpdateImpl.java:294)
    at ome.logic.UpdateImpl.doAction(UpdateImpl.java:312)
    at ome.logic.UpdateImpl.doAction(UpdateImpl.java:302)
    at ome.logic.UpdateImpl.saveObject(UpdateImpl.java:108)
    at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:241)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:116)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy93.saveObject(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:98)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy93.saveObject(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor980.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:179)
    at ome.services.throttling.Callback.run(Callback.java:56)
    at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
    at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:150)
    at ome.services.blitz.impl.UpdateI.saveObject_async(UpdateI.java:81)
    at sun.reflect.GeneratedMethodAccessor979.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at omero.cmd.CallContext.invoke(CallContext.java:59)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy94.saveObject_async(Unknown Source)
    at omero.api._IUpdateTie.saveObject_async(_IUpdateTie.java:122)
    at omero.api._IUpdateDisp.___saveObject(_IUpdateDisp.java:153)
    at omero.api._IUpdateDisp.__dispatch(_IUpdateDisp.java:389)
    at IceInternal.Incoming.invoke(Incoming.java:159)
    at Ice.ConnectionI.invokeAll(ConnectionI.java:2357)
    at Ice.ConnectionI.dispatch(ConnectionI.java:1208)
    at Ice.ConnectionI.message(ConnectionI.java:1163)
    at IceInternal.ThreadPool.run(ThreadPool.java:302)
    at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
    at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:643)
    at java.lang.Thread.run(Thread.java:722)

    serverExceptionClass = ome.conditions.OptimisticLockException
    message = You are not authorized to change the update event for ome.model.annotations.TagAnnotation:Id_2341 from ome.model.meta.Event:Id_68717 to ome.model.meta.Event:Id_68682
You may need to reload the object before continuing.
    backOff = 0
}
Traceback (most recent call last):
  File "./script", line 375, in <module>
    runScript()
  File "./script", line 363, in runScript
    message += processImages(client, scriptParams) + '\n'
  File "./script", line 217, in processImages
    channels, zselect, tselect, recalc, disableCdb)
  File "./script", line 166, in extractFeatures
    disableCdb)
  File "./script", line 86, in extractFeaturesOneChannel
    fids, features, ftset)
  File "/usr/lib/python2.6/site-packages/pyslid/database/direct.py", line 482, in update
    Answer = updateNameTag(conn, tag, DBfilename_new)
  File "/usr/lib/python2.6/site-packages/pyslid/database/direct.py", line 129, in updateNameTag
    conn.getUpdateService().saveObject(tag)
  File "/opt/omero/server/lib/python/omero/gateway/__init__.py", line 3460, in __call__
    return self.handle_exception(e, *args, **kwargs)
  File "/opt/omero/server/lib/python/omero/gateway/__init__.py", line 3457, in __call__
    return self.f(*args, **kwargs)
  File "/opt/omero/server/lib/python/omero_api_IUpdate_ice.py", line 107, in saveObject
    return _M_omero.api.IUpdate._op_saveObject.invoke(self, ((obj, ), _ctx))
omero.OptimisticLockException: exception ::omero::OptimisticLockException
{
    serverStackTrace = ome.conditions.OptimisticLockException: You are not authorized to change the update event for ome.model.annotations.TagAnnotation:Id_2341 from ome.model.meta.Event:Id_68717 to ome.model.meta.Event:Id_68682
You may need to reload the object before continuing.
    at ome.security.basic.OmeroInterceptor.managedEvent(OmeroInterceptor.java:1003)
    at ome.security.basic.OmeroInterceptor.checkManagedDetails(OmeroInterceptor.java:773)
    at ome.security.basic.OmeroInterceptor.resetDetails(OmeroInterceptor.java:316)
    at ome.security.basic.OmeroInterceptor.onFlushDirty(OmeroInterceptor.java:181)
    at org.hibernate.event.def.DefaultFlushEntityEventListener.invokeInterceptor(DefaultFlushEntityEventListener.java:372)
    at org.hibernate.event.def.DefaultFlushEntityEventListener.handleInterception(DefaultFlushEntityEventListener.java:349)
    at org.hibernate.event.def.DefaultFlushEntityEventListener.scheduleUpdate(DefaultFlushEntityEventListener.java:287)
    at org.hibernate.event.def.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:155)
    at org.hibernate.event.def.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:219)
    at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:99)
    at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
    at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1208)
    at ome.logic.UpdateImpl.afterUpdate(UpdateImpl.java:294)
    at ome.logic.UpdateImpl.doAction(UpdateImpl.java:312)
    at ome.logic.UpdateImpl.doAction(UpdateImpl.java:302)
    at ome.logic.UpdateImpl.saveObject(UpdateImpl.java:108)
    at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at ome.security.basic.EventHandler.invoke(EventHandler.java:154)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:111)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:108)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:241)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:116)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy93.saveObject(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:98)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy93.saveObject(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor980.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:179)
    at ome.services.throttling.Callback.run(Callback.java:56)
    at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
    at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:150)
    at ome.services.blitz.impl.UpdateI.saveObject_async(UpdateI.java:81)
    at sun.reflect.GeneratedMethodAccessor979.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:307)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at omero.cmd.CallContext.invoke(CallContext.java:59)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy94.saveObject_async(Unknown Source)
    at omero.api._IUpdateTie.saveObject_async(_IUpdateTie.java:122)
    at omero.api._IUpdateDisp.___saveObject(_IUpdateDisp.java:153)
    at omero.api._IUpdateDisp.__dispatch(_IUpdateDisp.java:389)
    at IceInternal.Incoming.invoke(Incoming.java:159)
    at Ice.ConnectionI.invokeAll(ConnectionI.java:2357)
    at Ice.ConnectionI.dispatch(ConnectionI.java:1208)
    at Ice.ConnectionI.message(ConnectionI.java:1163)
    at IceInternal.ThreadPool.run(ThreadPool.java:302)
    at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
    at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:643)
    at java.lang.Thread.run(Thread.java:722)

    serverExceptionClass = ome.conditions.OptimisticLockException
    message = You are not authorized to change the update event for ome.model.annotations.TagAnnotation:Id_2341 from ome.model.meta.Event:Id_68717 to ome.model.meta.Event:Id_68682
You may need to reload the object before continuing.
    backOff = 0
}
}}}
```

**Comment by pwalczysko** [comment]
After discussion with @manics . The above error is a bug which came to life due to a bug in OMERO.Web - allowing me to execute the script twice. I also did not understand the workflow concerning the necessity to tick the  `Enable advanced features` box first in order to make the `Disable ContentDB Update` - see my first comment above. 
When going through the workflow with this knowledge, it went fine and without errors. 

Filed a bug for the double execution of the same script dialog for @will-moore to deal with https://trac.openmicroscopy.org.uk/ome/ticket/11119.
I would try to sort out the `Enable advanced features` muddle, but otherwise ready to merge.

**Comment by manics** [comment]
>  I would try to sort out the Enable advanced features muddle, but otherwise ready to merge. 

According to [the scripting docs](https://www.openmicroscopy.org/site/support/omero4/developers/Modules/Scripts/StyleGuide.html#parameter-grouping-ordering):
"if the ‘parent’ parameter of a group is a boolean, then un-checking the check-box in the UI will disable the child parameters"

So if `Enable Advanced Options` is unticked you shouldn't be able to change any of the sub-options. If you bring up the feature calculation script in Insight this works, but not in web. I've opened [Trac 11121](https://trac.openmicroscopy.org.uk/ome/ticket/11121)

That said, the other Bool parameters (to enable selection of the C, Z, T) were the wrong way round, so I've now negated them. To see this working as intended run the script from Insight.

**Comment by joshmoore** [comment]
- Select Z and Select T default to 0 and with checkbox disabled
- Capitalization of "... Readout Channel instead of all" is a bit odd, but otherwise fine. Default is 0 and checkbox is disabled

Otherwise, all seems fine. I didn't do any execution but am happy to do so with some minor warnings about what I should or shouldn't do. Happy to either pass off to @pwalczysko, merge myself, or let others merge.

**Pull request merged**
