### PR TITLE
Support screens, plates, wells

### PR DESCRIPTION
**Pull request by manics**
Support feature calculation and searching for Screens, Plates, Wells. Note I couldn't find a way to test PlateAcquisitions.

Also allows filtering results by screens/plates, and also adds two shortcut buttons to deselect all projects/datasets or all screen/plates.

### CODE REVIEW

**Comment by pwalczysko** [comment]
The "Deselect All" button works okay for both Projects and Screens, but I would expect a "Select All" button as well (quite a logical complement).

**Comment by pwalczysko** [comment]
Although this is not to do with this PR, I really wish now I could break up the Feature Calculation and start a new Calculation on a smaller plate (now it takes half an hour already)

**Comment by manics** [comment]
I debated that, but all projects/screens are already selected by default, and the button is just a convenience method.

**Comment by pwalczysko** [comment]
The reason I wanted it there was that I used the Deselect All and then I though, uh, maybe this was not the best idea - I should have not done it - immediately was looking for Select All to reverse the damage. Unfortunately, this is quite typical user behaviour. But admittedly, not a big problem.

**Comment by pwalczysko** [comment]
The inability to start feature calculation on a Run is unpleasant, because Web does not show the thumbs of wells when Plate is selected, just when Run is selected. Thus, when starting to calculate the features, I cannot see the wells - not ideal.

**Comment by pwalczysko** [comment]
In summary, it works on screens and plates, I can search across both P/Ds and Screens/Wells and can refine the results nicely. 
The remarks above are concerned with user-friendliness rather than with bugs or functionality. 
The most annoying is the complicated workflow coming from the fact that I have to go to Runs to see the thumbs, then calculate features on Screens or Plates, but then I have to go back to Runs in order to see the thumbs (wells) in order to select the image I want to run a search for. This is not a workflow which a user will ever grasp without help/explanation.

But for this PR, I think it does what it says and fine to merge.

**Comment by manics** [comment]
It's easy enough to add a `select all` button, I was just worried about cluttering the UI.

**Comment by pwalczysko** [comment]
If you talk about the Select All button, there is a possibility to show the Select All button only and after Deselect All was pressed (maybe not optimal, but it does not clutter anything).

**Comment by manics** [comment]
That's not quite so straightforward, since if the user individually checks (or unchecks) all checkboxes the button would also need to change between select/deselect, in a similar way to how the checkboxes behave for datasets and projects. E.g. if you tick all datasets in a project the project gets ticked, if you untick all datasets in a project the project gets unticked. Unfortunately extending this to a third level (checkbox for all/no projects) is quite complicated, which si why I included the button as an imperfect workaround.

**Comment by pwalczysko** [comment]
Okay, that makes sense. I would leave as it is then.

**Comment by pwalczysko** [comment]
Works just as before.
I just noticed some thumb problem in the list:
screen shot 2014-01-20 at 15 13 26

**Comment by manics** [comment]
That's an ongoing problem.

**Comment by icaoberg** [comment]
is omero generating the thumbnails on the fly or caching them? is this a problem only with web or it happens with the clients as well?

**Comment by pwalczysko** [comment]
This is probably rather a question at @will-moore

**Comment by pwalczysko** [comment]
In my experience not a very common problem even in OMERO.web.

**Comment by will-moore** [comment]
What size are the thumbnails? Best to use size 96 (then you'll be getting ones that are already created and cached on the server). But using different size "shouldn't" cause a problem. What do you see if you open the src of a broken thumbnail in it's own window?

**Pull request merged**
