### PR TITLE
Export report 11338

### PR DESCRIPTION
**Pull request by manics**
https://trac.openmicroscopy.org.uk/ome/ticket/11338

Provide a quick and dirty way of viewing search results in CSV format. Ideally the CSV should appear in a popup instead of embedded in the page, but I can't work out how to do it without rewriting the form submission logic which uses ajax to update the middle pane. For now you can click in the middle pane, select all (Ctrl-A), paste into a plain text file name something.csv, and re-open in Excel.

Also adds a score column to the table. Note scores are not provided if a mix of +ve and -ve reference images are selected.

Note needs this Ricerca PR: https://github.com/icaoberg/ricerca/pull/1

Also includes #11

### CODE REVIEW

**Comment by mporter-gre** [comment]
Works as detailed, but would be nice if it contained project/dataset information in the output.

**Comment by manics** [comment]
Updated with parent (dataset) name. Also escape special characters. Push forced to remove extra commit which crept in. Currently broken because the installation script needs updating.

**Comment by manics** [comment]
This should hopefully be working now. The export button should export the current search results to a new CSV, which you should be prompted to open/save. The parent (i.e. dataset) name should also be included.

Note this PR includes PR #11, so ideally check that the additional user-filters still work.

**Comment by mporter-gre** [comment]
Checked filters, appear to work fine (excluded images by dataset and channel), and export to csv without problem.

**Pull request merged**
