### PR TITLE
Add omero-vm setup script

### PR DESCRIPTION
**Pull request by manics**
This is a setup script which can be used as part of the openmicroscopy buildvm target. See https://github.com/openmicroscopy/openmicroscopy/pull/1361

It's a bit of a mess due to limitations in the VM at the moment.

### CODE REVIEW

**Comment by manics** [comment]
--requires #9

**Comment by manics** [comment]
I'm not sure if the omero_searcher repo is the best place for an OME infrastructure specific (including several hacks/workarounds) build script. Maybe another repo for external build-related items?

**Comment by joshmoore** [comment]
Agreed, @manics, though I don't know a way other than having them either 1) all in ome.git which I'm not thrilled about or 2) in yet another integration repo of some form. If this were more standardized (like a specfile) then there would be much concern in hosting it in omero_searcher, I think. So perhaps this depends on where we're going with the VMs. If we're going to move to something else soon anyway, then I don't mind having a small number of these in ome.git temporarily, but the goal should be to have something in place that third-parties can do _in their own repos_ in order to make ever more sophisticated VMs (and hudson jobs).

/cc @Criswell, @stick, @mwoodbri, @sbesson, @kennethgillen

**Comment by manics** [comment]
If you want to switch to Centos VMs and build RPMs I've got no problem with that :)

**Comment by joshmoore** [comment]
:) Is there anything else I can do to test before the VM-build is working? Otherwise, I'm happy for this to go in and we can review later.

**Comment by manics** [comment]
Reverting the changes to `install.sh`, everything is now in #19

**Comment by joshmoore** [comment]
Post-conference ping.

**Pull request closed without merging**
